// <auto-generated />
using System;
using LibraryShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607080609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryShop.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1948,
                            FirstName = "Andrzej",
                            LastName = "Sapkowski"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1892,
                            FirstName = "J.R.R.",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1920,
                            FirstName = "Frank",
                            LastName = "Herbert"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1903,
                            FirstName = "George",
                            LastName = "Orwell"
                        });
                });

            modelBuilder.Entity("LibraryShop.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Price = 29.99m,
                            PublishedAt = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 15,
                            Title = "The Witcher: Blood of Elves"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Price = 29.99m,
                            PublishedAt = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 10,
                            Title = "The Witcher: Time of Contempt"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Price = 39.99m,
                            PublishedAt = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 20,
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Price = 39.99m,
                            PublishedAt = new DateTime(1954, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 18,
                            Title = "The Two Towers"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Price = 45.00m,
                            PublishedAt = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 8,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Price = 40.00m,
                            PublishedAt = new DateTime(1969, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 0,
                            Title = "Dune Messiah"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            Price = 24.99m,
                            PublishedAt = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 25,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            Price = 19.99m,
                            PublishedAt = new DateTime(1945, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 30,
                            Title = "Animal Farm"
                        });
                });

            modelBuilder.Entity("LibraryShop.Models.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Book_Category");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("LibraryShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dystopia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Political Satire"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Classic"
                        });
                });

            modelBuilder.Entity("LibraryShop.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.kowalska@example.com",
                            FirstName = "Anna",
                            LastName = "Kowalska"
                        },
                        new
                        {
                            Id = 2,
                            Email = "piotr.nowak@example.com",
                            FirstName = "Piotr",
                            LastName = "Nowak"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria.w@example.com",
                            FirstName = "Maria",
                            LastName = "Wiśniewska"
                        });
                });

            modelBuilder.Entity("LibraryShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            FulfilledAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2
                        });
                });

            modelBuilder.Entity("LibraryShop.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("OrderId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("Order_Item");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            BookId = 1,
                            Quantity = 2,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            OrderId = 1,
                            BookId = 7,
                            Quantity = 1,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            OrderId = 2,
                            BookId = 5,
                            Quantity = 1,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            OrderId = 3,
                            BookId = 3,
                            Quantity = 3,
                            UnitPrice = 39.99m
                        });
                });

            modelBuilder.Entity("LibraryShop.Models.Book", b =>
                {
                    b.HasOne("LibraryShop.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryShop.Models.BookCategory", b =>
                {
                    b.HasOne("LibraryShop.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryShop.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryShop.Models.Order", b =>
                {
                    b.HasOne("LibraryShop.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LibraryShop.Models.OrderItem", b =>
                {
                    b.HasOne("LibraryShop.Models.Book", "Book")
                        .WithMany("OrderItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LibraryShop.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryShop.Models.Book", b =>
                {
                    b.Navigation("BookCategories");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("LibraryShop.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("LibraryShop.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LibraryShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
